backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - label: "المقالات"
    name: "articles"
    # مؤقتًا هنخلّي CMS ينشئ ملفات مقالات منفصلة ليسهل التجربة
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "الصورة", name: "image", widget: "image", required: false }
      - { label: "المحتوى", name: "body", widget: "markdown" }
