backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "المقالات"
    folder: ""
    files:
      - file: "articles.json"
        label: "قائمة المقالات"
        name: "articles"
        fields:
          - { label: "ID", name: "id", widget: "string" }
          - { label: "العنوان", name: "title", widget: "string" }
          - { label: "المحتوى", name: "body", widget: "text" }
          - { label: "الصورة", name: "image", widget: "image", required: false }
