backend:
  name: git-gateway
  branch: main

media_folder: "uploads"      # مكان رفع الصور داخل الريبو
public_folder: "/uploads"    # المسار العام للصور على الموقع

locale: ar
editor:
  preview: false

collections:
  - name: "content"
    label: "المحتوى"
    files:
      - name: "articles"
        label: "المقالات"
        file: "articles.json"   # هنحرّر نفس الملف
        format: "json"
        extension: "json"
        fields:
          - label: "المقالات"
            name: "articles"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - { label: "المعرّف (لاتيني)", name: "id", widget: "string" }
              - { label: "العنوان", name: "title", widget: "string" }
              - { label: "الصورة",  name: "img", widget: "image", required: false }
              - { label: "النص",    name: "body", widget: "text" }
