backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

locale: "ar"

collections:
  - name: "articles"
    label: "المقالات"
    # هنحرر ملف JSON واحد اسمه articles.json
    files:
      - file: "articles.json"
        label: "كل المقالات"
        name: "articlesFile"
        format: "json"
        fields:
          - label: "المقالات"
            name: "articles"
            widget: "list"
            label_singular: "مقال"
            fields:
              - { label: "المعرّف (انجليزي)", name: "id", widget: "string" }
              - { label: "العنوان", name: "title", widget: "string" }
              - { label: "التصنيف/التاج", name: "tag", widget: "string", hint: "مثلاً: sun أو aries..."}
              - { label: "صورة (اختياري)", name: "image", widget: "image", required: false }
              - { label: "المحتوى", name: "body", widget: "markdown" }
