backend:
  name: git-gateway
  branch: main

site_url: https://egyptiantarot.com

media_folder: "assets/uploads"    # مكان حفظ الصور داخل الريبو
public_folder: "/assets/uploads"  # مكان عرض الصور على الموقع
locale: ar

collections:
  - name: "articles"
    label: "المقالات"
    files:
      - file: "articles.json"
        label: "قائمة المقالات"
        name: "articlesJson"
        format: "json"
        fields:
          - label: "المقالات"
            name: "articles"
            widget: "list"
            summary: "{{fields.title}} ({{fields.id}})"
            fields:
              - { label: "المعرّف (id)", name: "id", widget: "string" }
              - { label: "العنوان", name: "title", widget: "string" }
              - { label: "الوصف", name: "description", widget: "text" }
              - { label: "الصورة", name: "image", widget: "image" }
              - { label: "المحتوى", name: "content", widget: "markdown" }
