backend:
  name: git-gateway
  branch: main

media_folder: "content/uploads"
public_folder: "/content/uploads"

locale: "ar"

collections:
  - label: "المقالات"
    name: "articles"
    files:
      - label: "كل المقالات"
        name: "articlesFile"
        file: "articles.json"
        format: "json"
        fields:
          - label: "المقالات"
            name: "articles"
            widget: "list"
            collapsed: true
            allow_add: true
            fields:
              - { label: "المعرّف (لاتيني بلا مسافات)", name: "id", widget: "string" }
              - { label: "العنوان", name: "title", widget: "string" }
              - label: "الأيقونة"
                name: "img"
                widget: "select"
                options: ["sun", "moon", "star"]
                default: "sun"
              - label: "المحتوى (فقرات)"
                name: "body"
                widget: "list"
                field: { label: "فقرة", name: "paragraph", widget: "text" }
