backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"     # مكان حفظ الصور داخل الريبو
public_folder: "/assets/uploads"   # المسار العلني للصور على الموقع

locale: ar

collections:
  - name: "articles"
    label: "المقالات"
    files:
      - file: "articles.json"
        label: "قائمة المقالات"
        name: "articlesJson"
        format: "json"
        fields:
          - label: "المقالات"
            name: "articles"
            widget: "list"
            summary: "{{fields.title}} ({{fields.id}})"
            fields:
              - { label: "المعرف (id)", name: "id", widget: "string" }
              - { label: "العنوان", name: "title", widget: "string" }
              - { label: "الرمز (للمصغّرات)", name: "img", widget: "select", options: ["moon","sun","star"] }
              - { label: "صورة رئيسية (اختياري)", name: "image", widget: "image", required: false }
              - label: "المحتوى (فقرات)"
                name: "body"
                widget: "list"
                field: { label: "فقرة", name: "paragraph", widget: "text" }
